"""
Local Runner for GitHub Enterprise Inventory Script
Interactive script that prompts for configuration and runs the inventory collection locally.
"""

import os
import sys
import shutil
from pathlib import Path


def prompt_input(prompt_text, default=None, required=True):
    """Prompt user for input with optional default value."""
    if default:
        value = input(f"{prompt_text} [{default}]: ").strip()
        return value if value else default
    else:
        while True:
            value = input(f"{prompt_text}: ").strip()
            if value or not required:
                return value
            print("  This field is required. Please enter a value.")


def load_existing_env():
    """Load existing .env values if present."""
    env_values = {}
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    env_values[key.strip()] = value.strip()
    return env_values


def create_env_file(config):
    """Create or overwrite the .env file with provided configuration."""
    env_path = Path(__file__).parent / ".env"
    lines = [
        "# GitHub Enterprise Inventory - Local Configuration",
        f"# Generated by run_local.py",
        "",
        f"GITHUB_ENTERPRISE_NAME={config['enterprise_name']}",
        f"GITHUB_PATS={config['pats']}",
        f"GITHUB_API_URL={config['api_url']}",
        f"GITHUB_GRAPHQL_URL={config['graphql_url']}",
    ]

    if config.get("repo_csv"):
        lines.append(f"REPO_CSV_FILE={config['repo_csv']}")
    if config.get("org_csv"):
        lines.append(f"ORG_CSV_FILE={config['org_csv']}")
    if config.get("max_orgs"):
        lines.append(f"MAX_ORGS_TO_PROCESS={config['max_orgs']}")

    lines.append("")

    with open(env_path, "w") as f:
        f.write("\n".join(lines))

    print(f"\n[OK] Configuration saved to {env_path}")


def main():
    print("=" * 60)
    print("  GitHub Enterprise Inventory - Local Runner")
    print("=" * 60)
    print()

    # Check for existing .env
    existing = load_existing_env()
    if existing:
        print("[INFO] Found existing .env file with saved configuration.")
        use_existing = input("Use existing configuration? (y/n) [y]: ").strip().lower()
        if use_existing in ("", "y", "yes"):
            print("\nUsing existing .env configuration.")
            print(f"  Enterprise: {existing.get('GITHUB_ENTERPRISE_NAME', 'N/A')}")
            pat_count = len([p for p in existing.get('GITHUB_PATS', '').split(',') if p.strip()])
            print(f"  PATs configured: {pat_count}")
            print(f"  API URL: {existing.get('GITHUB_API_URL', 'https://api.github.com')}")
            print()

            # Ask if they want to limit orgs for testing
            max_orgs = input("Limit number of orgs to process? (0 = all) [0]: ").strip()
            if max_orgs and max_orgs != "0":
                os.environ["MAX_ORGS_TO_PROCESS"] = max_orgs

            run_inventory()
            return

    # Interactive configuration
    print("Enter your GitHub Enterprise configuration:\n")

    enterprise_name = prompt_input("Enterprise name (slug from URL)")

    print("\nEnter GitHub PAT(s). For multiple tokens, separate with commas.")
    print("Required scopes: repo, admin:org, admin:enterprise")
    pats = prompt_input("GitHub PAT(s)")

    api_url = prompt_input(
        "GitHub API URL",
        default="https://api.github.com",
    )

    graphql_url = prompt_input(
        "GitHub GraphQL URL",
        default="https://api.github.com/graphql",
    )

    repo_csv = prompt_input(
        "Repository CSV filename",
        default="github_inventory_repositories.csv",
        required=False,
    )

    org_csv = prompt_input(
        "Organization CSV filename",
        default="github_inventory_organizations.csv",
        required=False,
    )

    max_orgs = prompt_input(
        "Max orgs to process (0 = all, useful for testing)",
        default="0",
        required=False,
    )

    config = {
        "enterprise_name": enterprise_name,
        "pats": pats,
        "api_url": api_url,
        "graphql_url": graphql_url,
        "repo_csv": repo_csv,
        "org_csv": org_csv,
        "max_orgs": max_orgs if max_orgs and max_orgs != "0" else None,
    }

    # Save configuration
    save = input("\nSave configuration to .env file? (y/n) [y]: ").strip().lower()
    if save in ("", "y", "yes"):
        create_env_file(config)
    else:
        # Set environment variables for this run only
        os.environ["GITHUB_ENTERPRISE_NAME"] = config["enterprise_name"]
        os.environ["GITHUB_PATS"] = config["pats"]
        os.environ["GITHUB_API_URL"] = config["api_url"]
        os.environ["GITHUB_GRAPHQL_URL"] = config["graphql_url"]
        if config.get("repo_csv"):
            os.environ["REPO_CSV_FILE"] = config["repo_csv"]
        if config.get("org_csv"):
            os.environ["ORG_CSV_FILE"] = config["org_csv"]
        if config.get("max_orgs"):
            os.environ["MAX_ORGS_TO_PROCESS"] = config["max_orgs"]

    run_inventory()


def run_inventory():
    """Import and execute the main inventory script."""
    print("\n" + "=" * 60)
    print("  Starting Inventory Collection...")
    print("=" * 60 + "\n")

    # Ensure we're in the correct directory
    script_dir = Path(__file__).parent
    os.chdir(script_dir)

    try:
        from github_inventory import main as inventory_main
        inventory_main()
    except KeyboardInterrupt:
        print("\n\nOperation cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n[ERROR] {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
